export const SCHEMA_ENTITY_START_X = 96
export const SCHEMA_ENTITY_START_Y = 140

export const SCHEMA_ENTITY_START_POSITION = {
  x: SCHEMA_ENTITY_START_X,
  y: SCHEMA_ENTITY_START_Y,
}

export const SCHEMA_ENTITY_NODE_WIDTH = 544
export const SCHEMA_ENTITY_NODE_HEIGHT = 110
export const SCHEMA_LAYOUT_RANK_SEP = 250
export const SCHEMA_LAYOUT_NODE_SEP = 130
export const SCHEMA_LAYOUT_EDGE_SEP = 70
export const SCHEMA_LAYOUT_VERTICAL_GAP = 210
export const SCHEMA_LAYOUT_HORIZONTAL_GAP =
  SCHEMA_ENTITY_NODE_WIDTH + SCHEMA_LAYOUT_RANK_SEP
export const SCHEMA_DEFAULT_EXPIRATION_DURATION = '30d'

export const SCHEMA_NODE_ID_PREFIX = 'entity-'
export const SCHEMA_FIELD_ID_PREFIX = 'field-'
export const SCHEMA_DATA_FIELD_ID_PREFIX = 'data-'
export const SCHEMA_EDGE_ID_PREFIX = 'xy-edge__'
